### ISSUE TITLE
Pragma once

### ISSUE THREAD

**Issue by Louis-de-Lavenne-de-Choulot** [algosup/2022-2023-project-3-harfang3d-binding-Project-8-group#11]
A Pragma once, header file directive for the preprocessor to only include the file in one compilation is making the code crash because considered outside of header.

to reproduce :
`python3 tests.py --rust --linux --debug a1_basic_type_exchange`

For now it is commented on the side.

Pragma once is added line 450 of the rust.py file

<img width="598" alt="Screenshot 2023-02-03 at 14 37 46" src="https://user-images.githubusercontent.com/71769482/216616542-cf15e29d-d9fc-45f9-84f3-743cae424038.png">
<img width="935" alt="Screenshot 2023-02-03 at 14 37 07" src="https://user-images.githubusercontent.com/71769482/216616389-e60e2886-244c-48b1-883d-7a29a0e0effb.png">
<img width="624" alt="Screenshot 2023-02-03 at 14 38 39" src="https://user-images.githubusercontent.com/71769482/216616715-e8180051-0408-4fd2-a00b-770e3db6b7a1.png">

**Comment by leo-chartier** [comment]
fixed in commit 45804cb
